import { ref, computed } from 'vue';
import type { Ref, ComputedRef } from 'vue';
import api from '@/api';

// ==============================
// INTERFACES
// ==============================

// A single measure attached to an indicator for a specific course
export interface IndicatorMeasure {
  measureId: number;
  courseIndicatorId: number;
  courseCode: string;
  description: string;

  studentsMet: number;
  studentsExceeded: number;
  studentsBelow: number;

  met: number;
  exceeded: number;
  below: number;

  metPercentage: number;
  status: string;
  note?: string;
  recommendedAction?: string | null;
}


// A performance indicator + course pairing in the summary report
export interface IndicatorData {
  id: number;
  indicatorNumber: string;                  // e.g., "3.1"
  courseCode: string;
  studentCount?: number;                    // ADDED: Number of students in the course
  measures: IndicatorMeasure[];
}

// Outcome with nested indicator data
export interface OutcomeData {
  outcomeNumber: number;
  outcomeDescription: string;
  overallStatus: string;
  indicators: IndicatorData[];
  recommendedActions: string[];
}

// Final report root object
export interface SummaryReportData {
  semesterId: number;
  semesterName: string;
  academicYear: string;
  generatedDate: string;
  generatedBy: string[];
  outcomes: OutcomeData[];
}

interface SummaryReportProps {
  programId: number | Ref<number> | ComputedRef<number>;
  semesterId:
    | number
    | Ref<number | null>
    | ComputedRef<number | null>
    | null
    | undefined;
}

// ==============================
// COMPOSABLE
// ==============================

export function useSummaryReportData(props: SummaryReportProps) {
  const loading = ref(false);
  const error = ref<string | null>(null);
  const reportData = ref<SummaryReportData | null>(null);

  // Normalized props – always numbers
  const programId = computed(() =>
    typeof props.programId === 'number'
      ? props.programId
      : (props.programId as Ref<number>).value
  );

  const semesterId = computed(() => {
    if (typeof props.semesterId === 'number') return props.semesterId;
    if (!props.semesterId) return null;
    return (props.semesterId as Ref<number | null>).value;
  });

  // ==============================
  // UTILITY FUNCTIONS
  // ==============================

  function calculateMetPercentage(met: number, exceeded: number, below: number): number {
    const total = met + exceeded + below;
    if (total === 0) return 0;
    return Math.round(((met + exceeded) / total) * 1000) / 10; // 1 decimal place
  }

  function determineStatus(percentage: number): string {
    if (percentage >= 80) return 'Met comfortably';
    if (percentage >= 70) return 'Met';
    if (percentage >= 65) return 'Barely not met';
    return 'Not met';
  }

  function determineOutcomeStatus(indicators: IndicatorData[]): string {
    const allMeasures = indicators.flatMap(i => i.measures);
    if (allMeasures.length === 0) return 'No Data';

    const metCount = allMeasures.filter(
      m => m.status === 'Met comfortably' || m.status === 'Met'
    ).length;

    const percentage = (metCount / allMeasures.length) * 100;

    if (percentage >= 80) return 'MET';
    if (percentage >= 50) return 'Partially Met';
    return 'Not Met';
  }

  // ==============================
  // MAIN LOAD FUNCTION
  // ==============================

  async function loadReportData() {
    if (!programId.value || programId.value <= 0) {
      error.value = 'Invalid program ID';
      return;
    }

    if (!semesterId.value || semesterId.value <= 0) {
      error.value = 'Please select a semester';
      return;
    }

    loading.value = true;
    error.value = null;
    reportData.value = null;

    try {
      console.log('Loading summary report for program:', programId.value, 'semester:', semesterId.value);

      // ------------------------------
      // Load Semester
      // ------------------------------
      const semesterRes = await api.get('/semesters', {
        params: { id: semesterId.value }
      });

      const semester = semesterRes.data.data;

      if (!semester) throw new Error('Semester not found');

      // ------------------------------
      // Load Outcomes
      // ------------------------------
      const outcomesRes = await api.get(`/outcome/bySemester/${semesterId.value}`);
      const outcomes = outcomesRes.data.data ?? [];
      console.log('Loaded outcomes:', outcomes.length, outcomes);

      if (outcomes.length === 0) {
        error.value = 'No student outcomes found for this semester';
        loading.value = false;
        return;
      }

      // ------------------------------
      // Load Admin Names ("Generated by")
      // ------------------------------
      const adminsRes = await api.get(`/program/${programId.value}/admins`);
      const programAdmins = adminsRes.data.data ?? [];

      const adminNames: string[] = [];
      for (const admin of programAdmins) {
        try {
          const userRes = await api.get(`/users/${admin.userId}`);
          const user = userRes.data.data;

          const title = user.nameTitle || user.name_title || '';
          const first = user.nameFirst || user.firstName || '';
          const last = user.nameLast || user.lastName || '';

          adminNames.push([title, first, last].filter(Boolean).join(' '));
        } catch (err) {
          console.warn(`Failed to load admin user ${admin.userId}`);
        }
      }

      // ------------------------------
      // Load All Active Courses (once)
      // ------------------------------
      let allCourses: any[] = [];
      try {
        const coursesRes = await api.get('/courses/active', {
          params: {
            semesterId: semesterId.value,
            page: 0,
            size: 1000
          }
        });

        allCourses = coursesRes.data.content ?? coursesRes.data.data ?? [];
        console.log('Loaded active courses:', allCourses.length, allCourses);
      } catch (err: any) {
        throw new Error('Failed to load courses');
      }

      // ==============================
      // BUILD OUTCOME DATA
      // ==============================

      const outcomeDataArray: OutcomeData[] = [];

      for (const outcome of outcomes) {
        const indicatorsRes = await api.get('/performance-indicators/by-outcome/active', {
          params: { studentOutcomeId: outcome.id }
        });

        const indicators = indicatorsRes.data.data ?? [];
        console.log(`Outcome ${outcome.number}: found ${indicators.length} indicators`);
        const indicatorDataArray: IndicatorData[] = [];
        const recommendedActions: string[] = [];

        for (const indicator of indicators) {
          // find courses assessing this indicator
          for (const course of allCourses) {
            // Get sections for this course
            const sectionsRes = await api.get(`/section`, {
              params: { courseId: course.id }
            });
            const sections = sectionsRes.data.data.sections ?? [];


            if (sections.length === 0) break;

            // Get section IDs
            const sectionIds = sections.map((s: any) => s.id);


            // Get section-indicators for these sections that match this outcome's indicator
            const sectionIndicatorsRes = await api.get(`/section-indicator`, {
              params: {
                sectionIds: sectionIds,
                indicatorIds: [indicator.id]
              }
            });
            const sectionIndicators = sectionIndicatorsRes.data.data ?? [];


            if (sectionIndicators.length === 0) continue;

            // Get section-program relationships for these sections
            const sectionProgramRes = await api.get(`/section-program`, {
              params: {
                sectionId: sections[0].id, // Query by first section (all should have same program)
                programId: programId.value
              }
            });
            const sectionPrograms = sectionProgramRes.data.data ?? [];

            if (sectionPrograms.length === 0) continue;

            // Get section-program IDs
            const sectionProgramIds = sectionPrograms.map((sp: any) => sp.id);

            // Get measure results for these section-programs
            const measureResultsRes = await api.get(`/measure-result`, {
              params: {
                sectionProgramId: sectionProgramIds[0] // Use first section-program ID
              }
            });
            const measureResults = measureResultsRes.data.data ?? [];


            const matched = measureResults;

            const formattedMeasures: IndicatorMeasure[] = [];

            for (const measureResult of matched) {
              const met = measureResult.studentsMet;
              const exceeded = measureResult.studentsExceeded;
              const below = measureResult.studentsBelow;

              if (met == null || exceeded == null || below == null) continue;

              const pct = calculateMetPercentage(met, exceeded, below);
              const status = determineStatus(pct);

              const desc =
                measureResult.observation ||
                'No description';

              formattedMeasures.push({
                measureId: measureResult.id,
                courseIndicatorId: measureResult.sectionProgramId,
                courseCode: course.courseCode,
                description: desc,
                studentsMet: met,
                studentsExceeded: exceeded,
                studentsBelow: below,
                met,
                exceeded,
                below,
                metPercentage: pct,
                status,
                note: measureResult.observation ?? undefined,
                recommendedAction: measureResult.recommendedAction ?? null,
              });

              if (measureResult.recommendedAction) {
                recommendedActions.push(measureResult.recommendedAction);
              }
            }

            if (formattedMeasures.length > 0) {
              const indicatorNumber =
                indicator.indNumber ??
                indicator.indicatorNumber ??
                indicator.ind_number ??
                indicator.indicator_number;

              indicatorDataArray.push({
                id: indicator.id,
                indicatorNumber: `${outcome.number}.${indicatorNumber}`,
                courseCode: course.courseCode,
                studentCount: course.studentCount ?? 0,
                measures: formattedMeasures
              });
            }
          }
        }

        if (indicatorDataArray.length > 0) {
          outcomeDataArray.push({
            outcomeNumber: outcome.number,
            outcomeDescription: outcome.outDescription,
            overallStatus: determineOutcomeStatus(indicatorDataArray),
            indicators: indicatorDataArray,
            recommendedActions: [...new Set(recommendedActions)]
          });
        }
      }

      // ==============================
      // FINAL REPORT OBJECT
      // ==============================

      const academicYear =
        semester.academicYear
          ? `${semester.academicYear}-${(semester.academicYear + 1) % 100}`
          : new Date().getFullYear().toString();

      reportData.value = {
        semesterId: semesterId.value!,
        semesterName: semester.name,
        academicYear,
        generatedDate: new Date().toLocaleDateString('en-US'),
        generatedBy: adminNames.length ? adminNames : ['System Administrator'],
        outcomes: outcomeDataArray
      };

    } catch (err: any) {
      error.value = err.message ?? 'Failed to load summary report data';
    } finally {
      loading.value = false;
    }
  }

  return {
    loading,
    error,
    reportData,
    loadReportData
  };
}
